-- Baseline schema for game_db. Captures the live state of the database as of 2026-05-07
-- when versioned migrations were re-introduced. Subsequent schema changes go in V2, V3, etc.
--
-- Notes:
-- - On a fresh empty database Flyway runs this file as V1 to create all tables.
-- - On the existing dev/prod database Flyway baseline-on-migrate stamps V1 as already-applied
--   without re-executing it, since the tables already exist.
-- - Generated from `pg_dump -s --no-owner --no-acl --no-comments game_db`. The pg_dump
--   `\restrict`/`\unrestrict` psql meta-commands have been stripped (Flyway runs JDBC, not
--   psql); the SET preamble is harmless and left in place.
-- - INFRA32 schema-drift audit confirmed game_db has zero entity-vs-DB drift, so V1 captures
--   exactly what entities expect.

-- Original pg_dump preamble below:

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: collections; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.collections (
    id bigint NOT NULL,
    name character varying(200) NOT NULL
);


--
-- Name: collections_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.collections ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.collections_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: franchises; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.franchises (
    id bigint NOT NULL,
    name character varying(200) NOT NULL
);


--
-- Name: franchises_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.franchises ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.franchises_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: game_collections; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.game_collections (
    game_id bigint NOT NULL,
    collection_id bigint NOT NULL
);


--
-- Name: game_franchises; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.game_franchises (
    game_id bigint NOT NULL,
    franchise_id bigint NOT NULL
);


--
-- Name: game_game_modes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.game_game_modes (
    game_id bigint NOT NULL,
    game_mode_id bigint NOT NULL
);


--
-- Name: game_genres; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.game_genres (
    game_id bigint NOT NULL,
    genre_id bigint NOT NULL
);


--
-- Name: game_modes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.game_modes (
    id bigint NOT NULL,
    name character varying(100) NOT NULL
);


--
-- Name: game_modes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.game_modes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.game_modes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: game_platforms; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.game_platforms (
    game_id bigint NOT NULL,
    platform_id bigint NOT NULL
);


--
-- Name: game_player_perspectives; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.game_player_perspectives (
    game_id bigint NOT NULL,
    player_perspective_id bigint NOT NULL
);


--
-- Name: game_tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.game_tags (
    game_id bigint NOT NULL,
    tag_id bigint NOT NULL
);


--
-- Name: game_themes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.game_themes (
    game_id bigint NOT NULL,
    theme_id bigint NOT NULL
);


--
-- Name: games; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.games (
    id bigint NOT NULL,
    background_image character varying(500),
    cover_image_id character varying(255),
    created_at timestamp(6) without time zone,
    description text,
    developers text,
    esrb_rating character varying(50),
    igdb_id integer NOT NULL,
    name character varying(255) NOT NULL,
    rating numeric(4,2),
    released character varying(20),
    age_ratings text,
    category integer,
    dlc_ids text,
    expansion_ids text,
    multiplayer_modes text,
    parent_game_id integer,
    parent_game_name character varying(255),
    rating_count integer,
    release_dates text,
    screenshots text,
    similar_game_ids text,
    storyline text,
    total_rating numeric(4,2),
    total_rating_count integer,
    videos text,
    first_release_date bigint,
    hypes integer
);


--
-- Name: games_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.games ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.games_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: genres; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.genres (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    source character varying(10) DEFAULT 'IGDB'::character varying NOT NULL
);


--
-- Name: genres_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.genres ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.genres_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: platforms; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.platforms (
    id bigint NOT NULL,
    name character varying(100) NOT NULL
);


--
-- Name: platforms_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.platforms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.platforms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: player_perspectives; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.player_perspectives (
    id bigint NOT NULL,
    name character varying(100) NOT NULL
);


--
-- Name: player_perspectives_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.player_perspectives ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.player_perspectives_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sync_state; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sync_state (
    state_key character varying(255) NOT NULL,
    state_value character varying(255)
);


--
-- Name: tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tags (
    id bigint NOT NULL,
    name character varying(200) NOT NULL
);


--
-- Name: tags_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: themes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.themes (
    id bigint NOT NULL,
    name character varying(100) NOT NULL
);


--
-- Name: themes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.themes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.themes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: collections collections_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.collections
    ADD CONSTRAINT collections_pkey PRIMARY KEY (id);


--
-- Name: franchises franchises_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.franchises
    ADD CONSTRAINT franchises_pkey PRIMARY KEY (id);


--
-- Name: game_collections game_collections_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_collections
    ADD CONSTRAINT game_collections_pkey PRIMARY KEY (game_id, collection_id);


--
-- Name: game_franchises game_franchises_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_franchises
    ADD CONSTRAINT game_franchises_pkey PRIMARY KEY (game_id, franchise_id);


--
-- Name: game_game_modes game_game_modes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_game_modes
    ADD CONSTRAINT game_game_modes_pkey PRIMARY KEY (game_id, game_mode_id);


--
-- Name: game_genres game_genres_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_genres
    ADD CONSTRAINT game_genres_pkey PRIMARY KEY (game_id, genre_id);


--
-- Name: game_modes game_modes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_modes
    ADD CONSTRAINT game_modes_pkey PRIMARY KEY (id);


--
-- Name: game_platforms game_platforms_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_platforms
    ADD CONSTRAINT game_platforms_pkey PRIMARY KEY (game_id, platform_id);


--
-- Name: game_player_perspectives game_player_perspectives_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_player_perspectives
    ADD CONSTRAINT game_player_perspectives_pkey PRIMARY KEY (game_id, player_perspective_id);


--
-- Name: game_tags game_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_tags
    ADD CONSTRAINT game_tags_pkey PRIMARY KEY (game_id, tag_id);


--
-- Name: game_themes game_themes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_themes
    ADD CONSTRAINT game_themes_pkey PRIMARY KEY (game_id, theme_id);


--
-- Name: games games_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.games
    ADD CONSTRAINT games_pkey PRIMARY KEY (id);


--
-- Name: genres genres_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.genres
    ADD CONSTRAINT genres_pkey PRIMARY KEY (id);


--
-- Name: platforms platforms_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.platforms
    ADD CONSTRAINT platforms_pkey PRIMARY KEY (id);


--
-- Name: player_perspectives player_perspectives_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.player_perspectives
    ADD CONSTRAINT player_perspectives_pkey PRIMARY KEY (id);


--
-- Name: sync_state sync_state_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_state
    ADD CONSTRAINT sync_state_pkey PRIMARY KEY (state_key);


--
-- Name: tags tags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT tags_pkey PRIMARY KEY (id);


--
-- Name: themes themes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.themes
    ADD CONSTRAINT themes_pkey PRIMARY KEY (id);


--
-- Name: themes uk3estny12ybh85k7y8j6gyyrep; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.themes
    ADD CONSTRAINT uk3estny12ybh85k7y8j6gyyrep UNIQUE (name);


--
-- Name: platforms uk9a2sis9gryj6f8tiecq3lfhda; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.platforms
    ADD CONSTRAINT uk9a2sis9gryj6f8tiecq3lfhda UNIQUE (name);


--
-- Name: games ukbvsxurslcuc869oxybnh2433k; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.games
    ADD CONSTRAINT ukbvsxurslcuc869oxybnh2433k UNIQUE (igdb_id);


--
-- Name: collections ukddet6fvs2nj65hg90ew34sgjy; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.collections
    ADD CONSTRAINT ukddet6fvs2nj65hg90ew34sgjy UNIQUE (name);


--
-- Name: game_modes ukes61qak4be33biidqbg5huaj7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_modes
    ADD CONSTRAINT ukes61qak4be33biidqbg5huaj7 UNIQUE (name);


--
-- Name: player_perspectives ukna8rk5uarhnfnuqedgdrjy314; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.player_perspectives
    ADD CONSTRAINT ukna8rk5uarhnfnuqedgdrjy314 UNIQUE (name);


--
-- Name: genres ukpe1a9woik1k97l87cieguyhh4; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.genres
    ADD CONSTRAINT ukpe1a9woik1k97l87cieguyhh4 UNIQUE (name);


--
-- Name: franchises ukqdviaggjtiltkswsukwo8sbxy; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.franchises
    ADD CONSTRAINT ukqdviaggjtiltkswsukwo8sbxy UNIQUE (name);


--
-- Name: tags ukt48xdq560gs3gap9g7jg36kgc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT ukt48xdq560gs3gap9g7jg36kgc UNIQUE (name);


--
-- Name: idx_games_first_release_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_games_first_release_date ON public.games USING btree (first_release_date);


--
-- Name: game_tags fk2ouhy80wfy0vcnq2hn20wfymy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_tags
    ADD CONSTRAINT fk2ouhy80wfy0vcnq2hn20wfymy FOREIGN KEY (game_id) REFERENCES public.games(id);


--
-- Name: game_game_modes fk43gyq716yebefeqshpt82tcf8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_game_modes
    ADD CONSTRAINT fk43gyq716yebefeqshpt82tcf8 FOREIGN KEY (game_id) REFERENCES public.games(id);


--
-- Name: game_franchises fk5uksstf363l8uygsy3sij8h4t; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_franchises
    ADD CONSTRAINT fk5uksstf363l8uygsy3sij8h4t FOREIGN KEY (game_id) REFERENCES public.games(id);


--
-- Name: game_genres fk61pffxhqw7ijuxpjra43eudj2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_genres
    ADD CONSTRAINT fk61pffxhqw7ijuxpjra43eudj2 FOREIGN KEY (genre_id) REFERENCES public.genres(id);


--
-- Name: game_platforms fk8pjvmkhqim850aeg8uj38hwr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_platforms
    ADD CONSTRAINT fk8pjvmkhqim850aeg8uj38hwr FOREIGN KEY (game_id) REFERENCES public.games(id);


--
-- Name: game_platforms fkbtko240xm8r93w9wv3suke522; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_platforms
    ADD CONSTRAINT fkbtko240xm8r93w9wv3suke522 FOREIGN KEY (platform_id) REFERENCES public.platforms(id);


--
-- Name: game_player_perspectives fkby6ri67hf97ngxyugqnpsfa7i; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_player_perspectives
    ADD CONSTRAINT fkby6ri67hf97ngxyugqnpsfa7i FOREIGN KEY (player_perspective_id) REFERENCES public.player_perspectives(id);


--
-- Name: game_player_perspectives fkcyqb2hw093phbkleipcnk7l1h; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_player_perspectives
    ADD CONSTRAINT fkcyqb2hw093phbkleipcnk7l1h FOREIGN KEY (game_id) REFERENCES public.games(id);


--
-- Name: game_game_modes fkghprqw5p3h1k1n9gahjuk7vtf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_game_modes
    ADD CONSTRAINT fkghprqw5p3h1k1n9gahjuk7vtf FOREIGN KEY (game_mode_id) REFERENCES public.game_modes(id);


--
-- Name: game_collections fkhub3llcqihw4ds80boaxvf5w4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_collections
    ADD CONSTRAINT fkhub3llcqihw4ds80boaxvf5w4 FOREIGN KEY (collection_id) REFERENCES public.collections(id);


--
-- Name: game_franchises fki8631qmbwhsecbe0q8t2q9b7p; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_franchises
    ADD CONSTRAINT fki8631qmbwhsecbe0q8t2q9b7p FOREIGN KEY (franchise_id) REFERENCES public.franchises(id);


--
-- Name: game_tags fkid31n053yadgnxpx75uvvk2pv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_tags
    ADD CONSTRAINT fkid31n053yadgnxpx75uvvk2pv FOREIGN KEY (tag_id) REFERENCES public.tags(id);


--
-- Name: game_themes fko1lfuoxlux6v66jft06kxgq4k; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_themes
    ADD CONSTRAINT fko1lfuoxlux6v66jft06kxgq4k FOREIGN KEY (game_id) REFERENCES public.games(id);


--
-- Name: game_themes fkokt8p984vysghp5r18fedrxrw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_themes
    ADD CONSTRAINT fkokt8p984vysghp5r18fedrxrw FOREIGN KEY (theme_id) REFERENCES public.themes(id);


--
-- Name: game_genres fkql4d2eq6sbei0cfghuu8ard2i; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_genres
    ADD CONSTRAINT fkql4d2eq6sbei0cfghuu8ard2i FOREIGN KEY (game_id) REFERENCES public.games(id);


--
-- Name: game_collections fktmd8dw7oyr6pojto4581cnaj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_collections
    ADD CONSTRAINT fktmd8dw7oyr6pojto4581cnaj FOREIGN KEY (game_id) REFERENCES public.games(id);


--
-- PostgreSQL database dump complete
--


